import Head from "next/head";
import LoadingScreen from "../components/Index/LoadingScreen/LoadingScreen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingScreen />

      <main>
        <div className="w-44 h-44">
          <video controls width={"250"} preload="" src="../assets/wedding.mp4">
            <source src="" />
          </video>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
