import Head from "next/head";
import LoadingScreen from "../components/Index/LoadingScreen/LoadingScreen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingScreen />

      <main></main>

      <footer></footer>
    </div>
  );
}
