import React from "react";
import Head from "next/head";
import LoadingScreen from "../components/Index/LoadingScreen/LoadingScreen";
import Image from "next/image";
import SectionPresentation from "../components/Index/SectionPresentation/SectionPresentation";
import Header from "../components/Shared/Header/Header";
import SectionVideo from "../components/Index/SectionVideo/SectionVideo";
import SectionDivider from "../components/UI/SectionDivider/SectionDivider";
import SectionServices from "../components/Index/SectionServices/SectionServices";
import SectionTestimonies from "../components/Index/SectionTestimonies/SectionTestimonies";
import SectionStayTuned from "../components/Index/SectionStayTuned/SectionStayTuned";
import SectionSpacing from "../components/UI/SectionSpacing/SectionSpacing";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <LoadingScreen />

        <main className="bg-white">
          <SectionVideo />
          <SectionDivider />
          <SectionPresentation />
          <SectionSpacing />
          <SectionServices />
          <SectionDivider />
          <SectionTestimonies />
          <SectionSpacing />
          <SectionStayTuned />
          <div className="h-screen w-full bg-white" />
        </main>

        <footer></footer>
      </div>
    </>
  );
}
